name: Build and Deploy to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install DITA-OT
      run: |
        curl -LO https://github.com/dita-ot/dita-ot/releases/download/4.1.1/dita-ot-4.1.1.zip
        unzip dita-ot-4.1.1.zip
        mv dita-ot-4.1.1 dita-ot

    - name: Build DITA HTML5 output
      run: dita -i course_map.ditamap -f html5 -o out --args.css=customization/css/custom.css

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages
        force_orphan: true
